name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        :yellow_heart: Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are suggesting.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: The Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Example: I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false