name: Request for Comments
description: Create a request for comments for this project
title: "[RFC]: "
labels: ["RFC"]
body:
  - type: markdown
    attributes:
      value: |
        :yellow_heart: Thanks for taking the time to fill out this request for comments!
  - type: checkboxes
    attributes:
      label: Is there a related issue for this?
      description: Please search to see if an issue already exists for the feature you are suggesting.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Abstract
      description: |
          A general description of the RFC topic.
          What is the problem that this RFC is trying to address?
          Add a brief description of why it is necessary.
    validations:
      required: true
  - type: textarea
    attributes:
        label: Motivation
        description: |
            The description of some concrete use cases which have lead to the necessity of this RFC.
            Include as much background context which is relevant or necessary to understand the idea and design choices.
    validations:
        required: true
  -   type: textarea
      attributes:
          label: Technical Details
          description: |
              - Describe the idea in appropriate detail, how it fits in the overall architecture and how it aligns with the product vision.
              - Document in detail how the implementation of this RFC will be carried out.
              - The size of this may vary between a few sentences to multiple standalone subsections, depending on the scope of the change/addition.
      validations:
          required: true
  -   type: textarea
      attributes:
          label: Performance Considerations
          description: |
              As performance is one of our core values, performance considerations should be separately described, where applicable. Any limitations, or expected significant performance degradations should be listed here.
      validations:
          required: true
  -   type: textarea
      attributes:
          label: Impact on Existing Functionalities
          description: |
              Any impacts on existing functionality, breaking changes, or deviation from product vision should be documented here, alongside explanations why they cannot/should not be circumvented.
      validations:
          required: true
  -   type: textarea
      attributes:
          label: Open Questions
          description: |
              Any open questions that the submitter is seeking feedback for should be listed here in as much detail as possible, if applicable.
      validations:
          required: true