@startuml
'https://plantuml.com/class-diagram

package vertx {
    interface EventBus {
        publish( address, message)
    }
    interface SharedData {
        getAsyncMap()

        putInAsyncMap()
    }
    interface MessageCodec
}

package neonbee {

    class DeployerVerticle extends WatchVerticle {
        triggerDeployment
    }

    class Deployables

    class DeployableModule extends Deployables {
        fromJar()
    }

    class DeployableModels extends Deployables {
        scanClassPath()
        Map<String, byte[]> readModelPayloads()
        deploy()
    }

    class EntityModelManager {
        Map<String, EntityModel> reloadModels()
    }

    class EntityModel {
        CdsModel csnModel;
        Map<String, ServiceMetadata> edmxMap;
    }

    class EntityModelLoader {
        Map<String, EntityModel>> load()

        scanDir(Path path)

        loadModelFromBuffer(): new method
    }

    class EntityWrapperMessageCodec implements MessageCodec {
    }
}

package neonbee.changes {
    class SharedEntityModelManager extends EntityModelManager {

        reloadRemoteModels()

        mergeRemoteModels(Map<String, EntityModel> newModels)
    }
    class Timer {
        every5Minutes()
    }

    class DistributedFileSystem {
        pushChanges()

        /**
        contains relative path and
        content of distributed files
        */
        Map<String, byte[]> files

        obtainChanges()
    }
}



DeployerVerticle::observedCreateOrModify ..> DeployableModule::fromJar: 1
DeployableModule::fromJar ..> DeployableModels::scanClassPath: 2
DeployableModels::scanClassPath ..> DeployableModels::readModelPayloads: 3
DeployerVerticle::observedCreateOrModify ..> DeployableModels::deploy: 4
DeployableModels::deploy ..> EntityModelManager::registerModels: 5
EntityModelManager::registerModels ..> DistributedFileSystem::pushChanges: 6
DistributedFileSystem::pushChanges ..> SharedData::putInAsyncMap: 7
EntityModelManager::reloadModels ..> EventBus::publish: 6  EVENT_BUS_MODELS_LOADED_ADDRESS, local only

Timer::every5Minutes .right.> SharedEntityModelManager::reloadRemoteModels: 1
SharedEntityModelManager::reloadRemoteModels ..> DistributedFileSystem::obtainChanges: 2
DistributedFileSystem::obtainChanges ..> SharedData::getAsyncMap: 3
SharedEntityModelManager::reloadRemoteModels .right.> EntityModelLoader::loadModelFromBuffer: 4
SharedEntityModelManager::reloadRemoteModels ..> SharedEntityModelManager::mergeRemoteModels: 5
EntityWrapperMessageCodec ..> EntityModelManager



@enduml