# This workflow will lint the commit messages enforcing the conventional commit format
# See [1], [2] and [3] for more information
# [1] https://github.com/wagoid/commitlint-github-action
# [2] https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional
# [3] https://www.conventionalcommits.org/

name: Lint Commit Messages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
        with:
          configFile: '.github/workflows/.commitlintrc.json'