# This workflow will lint the commit messages enforcing the conventional commit format
# See [1], [2] and [3] for more information
# [1] https://github.com/wagoid/commitlint-github-action
# [2] https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional
# [3] https://www.conventionalcommits.org/

name: Lint Commit Messages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@416045160973f9fff174ac6698412cfe7181c3f3 # v4
        with:
          configFile: '.github/workflows/.commitlintrc.json'